on:
  workflow_dispatch:
  schedule:
    - cron: '13 * * * *'

name: italian-comuni-bot

jobs:
  post-tweet:
    runs-on: macOS-latest
    env:
      RENV_PATHS_ROOT: ~/Library/Application Support/renv
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ITALIANCOMUNI_BOT_API_KEY: ${{ secrets.ITALIANCOMUNI_BOT_API_KEY }}
      ITALIANCOMUNI_BOT_API_KEY_SECRET: ${{ secrets.ITALIANCOMUNI_BOT_API_KEY_SECRET }}
      ITALIANCOMUNI_BOT_ACCESS_TOKEN: ${{ secrets.ITALIANCOMUNI_BOT_ACCESS_TOKEN }}
      ITALIANCOMUNI_BOT_ACCESS_TOKEN_SECRET: ${{ secrets.ITALIANCOMUNI_BOT_ACCESS_TOKEN_SECRET }}
      ITALIANCOMUNI_BOT_GOOGLE_MAPS_API_KEY: ${{ secrets.ITALIANCOMUNI_BOT_GOOGLE_MAPS_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Cache Renv packages
        uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Tweet Italian Comuni Map
        run: |
          Rscript tweet-bot.R
      - name: store index of last tweeted comune
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add 'last-tweeted.txt'
          git commit -m "stored index of last tweeted map"
          git push
